apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: unified-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "a37b1eee27082425790c2340fbf6a03f-647572061.ap-northeast-2.elb.amazonaws.com"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: unified-routes
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - unified-gateway
  http:
    # Kiali (변경 없음)
    - match:
        - uri:
            prefix: "/kiali"
      route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001

    # Grafana (변경 없음)
    - match:
        - uri:
            prefix: "/grafana"
      route:
        - destination:
            host: grafana.istio-system.svc.cluster.local
            port:
              number: 3000

    # ArgoCD (변경 없음)
    - match:
        - uri:
            prefix: "/argocd"
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80

    # User API (서비스 이름 수정: user -> user-api-svc)
    - match:
        - uri:
            prefix: "/api/user"
      route:
        - destination:
            host: user-api-svc.default.svc.cluster.local
            port:
              number: 8080

    # Profile API (서비스 이름 수정: profile -> profile-api-svc)
    - match:
        - uri:
            prefix: "/api/profile"
      route:
        - destination:
            host: profile-api-svc.default.svc.cluster.local
            port:
              number: 8081

    # Frontend (루트 경로)
    # 서비스 이름과 포트 수정: front:80 -> k8s-front-svc:3000
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: k8s-front-svc.default.svc.cluster.local
            port:
              number: 80
